# CSC3831 - Practical I
Hello Class, welcome to the first practical session, By this point you should have found the github for Part I. For this practical please read the information in the text blocks, and run the code blocks in sequence.

In this part of the course we will use a few Python packages. The packages used are as follows:
- [Pandas](https://pandas.pydata.org/): Data manipulation and analysis tool
- [Matplotlib](https://matplotlib.org/): Data visualisation tool
- [Seaborn](https://seaborn.pydata.org/index.html): Data visualisation tool

**Pandas** is one of the most popular data manpiulation libraries that researchers and practitioners use. Due to its popularity, Pandas `DataFrame` works as an input to most other analysis and graphics tools.

**Matplotlib** is an extremely popular plotting tool with axis, scaling, subplots, and positioning built in. Matplotlib gives you almost complete control over how you want to graph things, but can be a little complicated to get nice looking graphics.

**Seaborn** is an extremely popular graphing tool which provides nice looking graphics without much difficulty.

As stated in Lecture I, we will be using the [Iris Flower dataset](https://gist.github.com/curran/a08a1080b88344b0c8a7) to walk you through some basic analysis in Python, with the end of today's practical giving you the freedom to perform the same on a Titanic dataset.

### Loading packages and data
Let us start with loading our packages as well as the Iris dataset.

In [ ]:
# Loading packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Commonly in online tutorials as well as tutorials of the relevant packages, Pandas is shorthanded as "pd", Matplotlib shorthanded as "plt", and Seaborn is shorthanded as "sns", following this convention we will do the same in the tutorial. It is not necessary to do so, but following convention makes the interpretability of your code by others much simpler.

The version of the Iris dataset we are using is being hosted on the University of California Irvine (UCI) School of Informatics & Computer Science website.
Looking at the [data](http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data) itself, we can see the data\set is represented with **C**omma **S**eperated **V**alues or csv. While the file extension (what comes after the last period in a file name) is not csv but instead .data, the data itself is stored in csv format and can be parsed using a csv parser.

![Screenshot 2024-09-25 at 10.17.50.png]()

The Pandas library contains a csv parser called `read.csv`. For this practical we can understand it to, by default, turn a csv document into a Pandas dataframe with the first line of the data taken to represent the **attribute names**.

Looking at the raw data, the attribute names are not present so we must add them in manually using the `names` field.

In [ ]:
# Loading Iris Dataset
iris_url = "http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
col_names = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Class']
iris = pd.read_csv(iris_url, names = col_names)


So now we have turned our raw data into a DataFrame object with the appropriate attribute names. But what are Pandas DataFrames? In your previous computing courses, you should have learned about one-dimensional data structures like lists (e.g. arrays, linked-lists) and and two-dimensional structures like matrices (e.g. nested arrays).

Pandas provides one and two dimensional data structures via [`Series`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) and [`DataFrame`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html). The advantage of using Pandas data structures over the default Python is the ease of attribute and entity selection, as well as the basic statistics built into these data structures.

### Let's Take a Peek
Moving into some basic analysis, the first thing you should do when given a new set of data is take a peak at the data itself. After loading the data into Pandas, we can look at the top 10 rows by using the `.head(10)` method.

In [ ]:
iris.head(10)

From the `head` method, we can see the DataFrame's indices located to the far left of the output (the column without a header), as well as the values from each attribute. We can see that the following attributes [`Sepal_Length`, `Sepal_Width`, `Petal_Length`, `Petal_Width`] are decimal **numeric** values, whereas the `Class` attribute is **nominal** (categorical).

In Lecture I we discussed how finding the center, spread, and skew of our data is important before continuing analysis. We can use Seaborn [`.pairplot(data)`](https://seaborn.pydata.org/generated/seaborn.pairplot.html) to get a Paris plot of the data as well as Pandas [`data.describe.()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html) to get our Five Number Summary.

In [ ]:
sns.pairplot(iris)

Looking at the Pairs plot, we can see that only the numerical values were graphed above. This makes sense, as nominal values cannot be graphed against numerical in a scatter plot.

We can see that the top right traingle and the bottom left trianlge of scatter plots are a reflection of each other over the y=x line so it's fine to just look at one or the other. The main diagonal shows histograms of the values (i.e. the value plotted against itself) and can demonstrate the skew present in each attribute. From a cursorary glance, it looks like `Sepal_Length` and `Sepal_Width` are approximately normal (symmetric), but `Petal_Length` and `Petal_Width` have left skew.

To make the skew more evident we can graph the density plot for each attribute.

In [ ]:
sns.kdeplot(iris['Sepal_Length'])

In [ ]:
sns.kdeplot(iris['Sepal_Width'])

In [ ]:
sns.kdeplot(iris['Petal_Length'])

In [ ]:
sns.kdeplot(iris['Petal_Width'])

In [ ]:
iris.describe()

The `describe` method outputs some summary statistics of the numeric values. We know that mean and standard deviation should be used for normal values, but median (50% percentile) and MAD should be used for skewwed data.

Unfortunately, MAD has been depreciated in Pandas, but this gives us a good oppertunity to learn to how calculate it ourselves as well as index through a Pandas `DataFrame`.

In [ ]:
iris.columns[:-1]

In [ ]:
iris_MAD = pd.DataFrame(columns = iris.columns[:-1])
mads = []
for attribute in iris.columns[:-1]:
  mad = 1.483 * abs(iris[attribute] - iris[attribute].median()).median()
  mads.append(mad)
iris_MAD.loc[0] = mads
print(iris_MAD)

As `Sepal_Length` and `Sepal_Width` are approximately normal, and `Petal_Length` and `Petal_Width` are left skewed (binomal - having two humps in the data rather than one), when talking about center and spread of the values mean and standard devation should be used for the first two whereas median and MAD should be used for the latter two.

In Lecture/Practical 3 we will investigate scenarios where outliers can be removed from the dataset to remove skew, but in this case if we remove the smaller humps to the left it would remove a significant enough amount of data that doing so wouldn't be worthwhile.

### Determining Relationships in the Data

Next, we want to see if there is any evidence of relationships present in the data. Via our pairs plot, there seems to be some sort of correlation between attributes like Petal_Length and Sepal_Length, or Petal_Width and Petal_Length. Using the Pandas `.corr()` method we can get the correlation of all attributes against each other, which will show us the strength of a linear relationship as well as the direction (positive indicating that as the x-axis increases the y-axis also increases also known as a **positive relationship**, negaitve indicating that as the x-axis increases the y-axis decreases also known as a **negative relationship**)

In [ ]:
iris.corr()

When you ran that previous code blocks you should have received an error `ValueError: could not convert string to float: 'Iris-setosa'`. Looking at the `head` from earlier, we can see that is one of the values from the `Class` attribute in the data, which we know is nominal. Seaborn is smart enough to recognize nominal attributes and remove them from a Pairs plot, but Pandas `.corr()` Correlation can only be calculated for numerical attributes, so in order to find our correlations let's drop the nominal Class to just compare on numerics.

In [ ]:
iris_num = iris.drop(columns=["Class"])
iris_num.corr()

Similarly to the Pairs plot, `.corr()` returns all of the correlations with the bottom left triangle and top right computing the same thing. The main diagonal is always perfectly correlated (which makes sense as an attribute will vary the exact same amount with itself), so by looking at the correlations between different attributes we can assess the strength of that correlation as well as the direction. Correlation is a meassure from -1 to 1, with values close to 0 in either direction representing a weak correlation (i.e. little evidence that the values vary with respect to each other) and values close to -1 or 1 representing a strong correlation (i.e. greater evidence that the values vary with respect to each other).

Look at our correlations, we can acertain that there are strong positive correlations for `Petal_Length` vs `Petal_Width`, `Petal_Length` vs `Sepal_Length`, and `Petal_Width` vs `Sepal_Length`. We can also see that there are week negative correlations for `Sepal_Width` vs `Sepal_Length`, `Petal_Length` vs `Sepal_Width`, and `Petal_Width` vs `Sepal_Width`.

### Looking Smaller

Now we've seen the correlation between the numeric values for all of the different kinds of Iris, lets see if there is any difference when we break them up by genis (type of flower). The nominal `Class` attribute describes the type of Iris, so by graphing a bar plot of the values in `Class` we can determine which Iris types represent the most and the least entities in our data.

In [ ]:
sns.barplot(iris["Class"])

We can see from the above bar plot that `Iris-virginica` is the most represented Iris type in the dataset (with over 120 entities being `Iris-virginica` and `Iris-setosa` is the least. We can isolate these types into two seperate DataFrame objects using pattern matching.

In [ ]:
iris_virginica = iris[iris['Class'].str.contains("Iris-virginica")].drop(columns=["Class"])
iris_virginica.corr()

In [ ]:
iris_setosa = iris[iris['Class'].str.contains("Iris-setosa")].drop(columns=["Class"])
iris_setosa.corr()

Looking at the correlations after seperating the Iris types out, we can see that except for `Petal_width` vs `Sepal_legnth`, every relationship has changed in intensity.

It can be good to divide your numerical data into subgroups based upon the nominal classifications in the data. While they might not be graphical numerically, nominal values can tell us a lot about the data and here's one way to explore that further.

## Try things yourself!

In this practical we have
- Loaded the data
- Looked at summary statis
- Used a few graphics tools
- Talked about numeric and nominal values
- Analysed correlation in numeric data
- Compared the correlation in the data between subgroups

Please feel free to use this time to explore the data further yourself. There are plenty of interesting graphics in Seaborn and Matplotlib that we have not explored here, as well as analysis and stats in Pandas.

If you would like a further challenge, [here](https://github.com/datasciencedojo/datasets/blob/master/titanic.csv) is the link to the Titanic dataset which you can explore. Make your own decisions about how to explore the data, and provide your rationales for what you do. A few example questions you could analyse would be:
- Which class was most likely to surive?
- How many people your age survived and died?
- Is there any relations in the data which might suggest survival?

In [ ]:
titanic_file = "https://github.com/datasciencedojo/datasets/blob/master/titanic.csv"